### ISSUE TITLE
Make PDF

### ISSUE THREAD

**Issue by steveharoz** [journalovi/journalovi.github.io#2]
jupyter books have a button to print as PDF (see [here](https://the-turing-way.netlify.app/reproducible-research/overview/overview-barriers)).

Would it be possible to add that to the template? 

Maybe it could go in the footer, so a probably rarely used feature doesn't cause clutter.

**Comment by mjskay** [comment]
there are multiple format output options in quarto including PDF, so in theory something like this should be possible
