### ISSUE TITLE
Clearer contact info

### ISSUE THREAD

**Issue by mjskay** [journalovi/journalovi.github.io#28]
including emails (currently at top of Organizers page) and link to the github repo for issues.

TODOs:

- ~~[ ] add the github link to the top of the organizers page~~ (not necessary I think --- the links are now on every page)
- [x] add the github icon to all pages

**Comment by floe** [comment]
BTW, if we're adding a footer or similar, should we also put a default copyright notice with CC-BY[-SA] on every page?
