### ISSUE TITLE
Broken Mastodon link?

### ISSUE THREAD

**Issue by floe** [journalovi/journalovi.github.io#45]
The link in the header just goes to "https://hci.social", without the username, but the Quarto file actually contains the correct link: https://github.com/journalovi/journalovi.github.io/blob/f7bd6a2fb3fc8c979df30d5ce1b2a1bc4a076a10/_quarto.yml#L24
Not sure what's going on here. Some kind of YML parser hiccup? Maybe try "https://hci.social/@jovi/" as link with trailing slash?

**Comment by mjskay** [comment]
good catch, url-encoding the at symbol seems to fix it. see #46
